server:
  port: 8089
  servlet:
    context-path: /


#spring配置
spring:
  application:
    name: elderlyCare
    version: 1.0.0
    description: "老年人管理系统Ops"
  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eldercaresystem?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: root
  #redis配置
  redis:
    host: localhost
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#mybatisplus配置
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:xml/*/*.xml

#swagger配置开关
swagger:
  opened: true


logging:
  config: classpath:logging-spring.xml
#  level: debug


#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: shutdown
